import type { MerchantData } from '@/src/types';
import { initialMerchantData } from '@/src/types';

/**
 * Demo profiles for presentations and manual testing.
 *
 * Pick a profile from the Merchant portal sidebar. The "Autofill" shortcut
 * then only fills the fields of the CURRENT intake step so you can step
 * through the wizard with realistic values one page at a time.
 *
 * Text/dropdown/button questions fill a single field; form steps fill all
 * fields in that form. Files are intentionally left null so the Admin view
 * can still show "missing documents".
 */
export interface DemoProfile {
  id: string;
  label: string;
  description: string;
  data: MerchantData;
}

const northwindSaasCanada: MerchantData = {
  ...initialMerchantData,
  businessType: 'llc',
  country: 'CA',
  industry: 'software',
  monthlyVolume: '10k-50k',
  monthlyTransactions: '100-1k',
  legalName: 'Northwind Analytics Inc.',
  dbaName: 'Northwind Analytics',
  taxId: 'BN 123456789',
  businessRegistrationNumber: 'BC1234567 / GST 123456789 RT0001',
  establishedDate: '2021-04-15',
  legalBusinessAddress: '400 Granville Street, Suite 1200, Vancouver, BC',
  operatingAddressDifferent: 'No',
  businessPhone: '+1 604 555 0142',
  legalBusinessEmail: 'legal@northwind-demo.example',
  ownerName: 'Alex Chen',
  website: 'https://northwind-demo.example',
  staffSize: '18',
  paymentProducts: 'Cards, ACH, Apple Pay',
  businessCategory: 'B2B SaaS — analytics',
  productsServices: 'Subscription analytics software for small finance teams.',
  goodsOrServicesType: 'Digital goods / services',
  customerType: 'B2B',
  advancePayment: 'Yes',
  advancePaymentPercent: '100% monthly subscription paid at billing date',
  recurringBilling: 'Yes',
  recurringSalesPercent: '95%',
  fulfillmentTimeline: 'Immediate account access after signup',

  generalEmail: 'hello@northwind-demo.example',
  supportEmail: 'support@northwind-demo.example',
  disputesEmail: 'risk@northwind-demo.example',
  phone: '+1 604 555 0142',
  preferredContact: 'Email',
  socialPresence: 'LinkedIn, X',

  registeredAddress: '400 Granville Street, Suite 1200',
  operatingAddress: 'Same as registered',
  city: 'Vancouver',
  region: 'BC',
  province: 'British Columbia',
  operatingDiffers: 'no',

  timeInBusiness: '3 years',
  targetGeography: 'Canada & United States',
  deliveryMethod: 'N/A — digital product',
  domesticVsInternational: '85% domestic / 15% international',

  avgTxnCount: '450',
  minTxnCount: '200',
  maxTxnCount: '900',
  avgTicketSize: '89',
  domesticCrossBorderSplit: '85% domestic / 15% cross-border',
  processingCurrencies: 'CAD, USD',
  highestTicketAmount: '1200',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Visa, Mastercard, Amex, Apple Pay',
  recurringTransactionsPercent: '95%',
  foreignCardsPercent: '15%',

  recurringBillingDetails: 'Monthly and annual SaaS subscriptions',
  trialPeriod: '14-day trial',
  refundPolicy: 'Pro-rated refunds within 30 days',
  shippingPolicy: 'N/A',

  ownershipPercentage: '100',
  beneficialOwners: 'Alex Chen, 100%, CEO & Founder, alex.chen@northwind-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Alex Chen',
  authorizedSignerTitle: 'CEO & Founder',
  authorizedSignerEmail: 'alex.chen@northwind-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'CEO & Founder',
  ownerEmail: 'alex.chen@northwind-demo.example',
  ownerIdNumber: 'DL-BC-DEMO-90210',
  ownerIdExpiry: '2028-06-30',
  ownerCountryOfResidence: 'CA',

  bankName: 'TD Canada Trust',
  accountHolderName: 'Northwind Analytics Inc.',
  accountNumber: '****4521 (demo)',
  routingNumber: '004',
  settlementCurrency: 'CAD',

  complianceDetails: 'SOC 2 Type II in progress; vendor security reviews annually.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Stripe',
  processorExitReason: 'Looking for better Canadian settlement support and processor fit.',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Stripe Billing, hosted checkout',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

const brightHarborRetailUs: MerchantData = {
  ...initialMerchantData,
  businessType: 'corporation',
  country: 'US',
  industry: 'retail',
  monthlyVolume: '50k-250k',
  monthlyTransactions: '1k-10k',
  legalName: 'Bright Harbor Goods, Inc.',
  dbaName: 'Bright Harbor',
  taxId: '47-8812993',
  businessRegistrationNumber: 'DE-4482217 / EIN 47-8812993',
  establishedDate: '2019-08-02',
  legalBusinessAddress: '221 W 4th Street, Suite 301, Wilmington, DE 19801',
  operatingAddressDifferent: 'Yes',
  businessPhone: '+1 302 555 0188',
  legalBusinessEmail: 'legal@brightharbor-demo.example',
  ownerName: 'Priya Natarajan',
  website: 'https://brightharbor-demo.example',
  staffSize: '42',
  paymentProducts: 'Cards, Apple Pay, Google Pay, Shop Pay',
  businessCategory: 'Direct-to-consumer home goods retailer',
  productsServices: 'Curated kitchen and home goods sold via Shopify + Amazon.',
  goodsOrServicesType: 'Physical goods',
  customerType: 'B2C',
  advancePayment: 'No',
  advancePaymentPercent: '0%',
  recurringBilling: 'No',
  recurringSalesPercent: '0%',
  fulfillmentTimeline: '2–5 business days, tracked shipping',

  generalEmail: 'hello@brightharbor-demo.example',
  supportEmail: 'care@brightharbor-demo.example',
  disputesEmail: 'disputes@brightharbor-demo.example',
  phone: '+1 302 555 0188',
  preferredContact: 'Email',
  socialPresence: 'Instagram, TikTok, Pinterest',

  registeredAddress: '221 W 4th Street, Suite 301',
  operatingAddress: '880 Industrial Way, Reno, NV 89502 (fulfillment center)',
  city: 'Wilmington',
  region: 'DE',
  province: 'Delaware',
  operatingDiffers: 'yes',

  timeInBusiness: '6 years',
  targetGeography: 'United States (all 50 states) + limited CA shipping',
  deliveryMethod: 'In-house fulfillment + 3PL (ShipBob)',
  domesticVsInternational: '95% domestic / 5% cross-border',
  avgDeliveryTime: '3 business days',

  avgTxnCount: '3200',
  minTxnCount: '1800',
  maxTxnCount: '6500',
  avgTicketSize: '68',
  domesticCrossBorderSplit: '95% domestic / 5% cross-border',
  processingCurrencies: 'USD',
  highestTicketAmount: '840',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Visa, Mastercard, Amex, Discover, Apple Pay, Google Pay',
  recurringTransactionsPercent: '0%',
  foreignCardsPercent: '8%',

  refundPolicy: '30-day no-questions-asked returns, prepaid label included',
  shippingPolicy: 'Free US ground shipping on orders $50+',

  ownershipPercentage: '60',
  beneficialOwners:
    'Priya Natarajan, 60%, CEO, priya@brightharbor-demo.example\nMarcus Lee, 40%, COO, marcus@brightharbor-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Priya Natarajan',
  authorizedSignerTitle: 'CEO',
  authorizedSignerEmail: 'priya@brightharbor-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'CEO & Co-founder',
  ownerEmail: 'priya@brightharbor-demo.example',
  ownerIdNumber: 'DL-DE-DEMO-44219',
  ownerIdExpiry: '2029-02-14',
  ownerCountryOfResidence: 'US',

  bankName: 'Chase',
  accountHolderName: 'Bright Harbor Goods, Inc.',
  accountNumber: '****7788 (demo)',
  routingNumber: '021000021',
  settlementCurrency: 'USD',

  complianceDetails: 'PCI DSS SAQ A via Shopify; annual vendor security review.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Shopify Payments',
  processorExitReason: 'Seeking lower interchange on Amex and better chargeback tooling.',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Yes',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Shopify Payments, Shop Pay, Amazon Pay',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

const helixProServicesCanada: MerchantData = {
  ...initialMerchantData,
  businessType: 'partnership',
  country: 'CA',
  industry: 'services',
  monthlyVolume: '<10k',
  monthlyTransactions: '<100',
  legalName: 'Helix Professional Services LLP',
  dbaName: 'Helix Pro',
  taxId: 'BN 998877665',
  businessRegistrationNumber: 'ON-LLP-2233445',
  establishedDate: '2023-01-10',
  legalBusinessAddress: '77 King Street West, Suite 2200, Toronto, ON',
  operatingAddressDifferent: 'No',
  businessPhone: '+1 416 555 0101',
  legalBusinessEmail: 'legal@helixpro-demo.example',
  ownerName: 'Dana Whitfield',
  website: 'https://helixpro-demo.example',
  staffSize: '4',
  paymentProducts: 'Cards, ACH',
  businessCategory: 'Management consulting',
  productsServices: 'Fractional CFO and finance operations consulting for SMBs.',
  goodsOrServicesType: 'Services',
  customerType: 'B2B',
  advancePayment: 'Yes',
  advancePaymentPercent: '50% deposit on engagement',
  recurringBilling: 'Yes',
  recurringSalesPercent: '60%',
  fulfillmentTimeline: 'Engagement kickoff within 1 week of payment',

  generalEmail: 'hello@helixpro-demo.example',
  supportEmail: 'clients@helixpro-demo.example',
  disputesEmail: 'billing@helixpro-demo.example',
  phone: '+1 416 555 0101',
  preferredContact: 'Email',
  socialPresence: 'LinkedIn',

  registeredAddress: '77 King Street West, Suite 2200',
  operatingAddress: 'Same as registered',
  city: 'Toronto',
  region: 'ON',
  province: 'Ontario',
  operatingDiffers: 'no',

  timeInBusiness: '2 years',
  targetGeography: 'Canada, primarily Ontario & BC',
  deliveryMethod: 'N/A — services engagement',
  domesticVsInternational: '100% domestic',

  avgTxnCount: '22',
  minTxnCount: '10',
  maxTxnCount: '45',
  avgTicketSize: '2800',
  domesticCrossBorderSplit: '100% domestic / 0% cross-border',
  processingCurrencies: 'CAD',
  highestTicketAmount: '12000',
  transactionChannelSplit: '0% card present / 60% e-commerce (invoice) / 40% MOTO',
  paymentTypesWanted: 'Visa, Mastercard, Amex',
  recurringTransactionsPercent: '60%',
  foreignCardsPercent: '0%',

  serviceType: 'Fractional CFO retainer + project-based finance ops',
  billingModel: 'Monthly retainer + milestone billing',
  contractLength: '6 months',

  ownershipPercentage: '55',
  beneficialOwners:
    'Dana Whitfield, 55%, Managing Partner, dana@helixpro-demo.example\nJordan Park, 45%, Partner, jordan@helixpro-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Dana Whitfield',
  authorizedSignerTitle: 'Managing Partner',
  authorizedSignerEmail: 'dana@helixpro-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'Managing Partner',
  ownerEmail: 'dana@helixpro-demo.example',
  ownerIdNumber: 'DL-ON-DEMO-55117',
  ownerIdExpiry: '2027-11-20',
  ownerCountryOfResidence: 'CA',

  bankName: 'RBC Royal Bank',
  accountHolderName: 'Helix Professional Services LLP',
  accountNumber: '****0204 (demo)',
  routingNumber: '003',
  settlementCurrency: 'CAD',

  complianceDetails: 'Standard professional services engagement letters; no regulated activity.',
  currentlyProcessesCards: 'No',
  currentOrPreviousProcessor: '',
  processorExitReason: 'First-time processor — moving from e-transfer and wire only.',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'None — will use hosted checkout',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Not applicable',
};

const orbitExchangeCryptoEu: MerchantData = {
  ...initialMerchantData,
  businessType: 'corporation',
  country: 'EU',
  industry: 'crypto',
  monthlyVolume: '>250k',
  monthlyTransactions: '>10k',
  legalName: 'Orbit Exchange OÜ',
  dbaName: 'Orbit',
  taxId: 'EE102334455',
  businessRegistrationNumber: 'EE-14778822 / VAT EE102334455',
  establishedDate: '2018-06-22',
  legalBusinessAddress: 'Tornimäe 5, 10145 Tallinn, Estonia',
  operatingAddressDifferent: 'Yes',
  businessPhone: '+372 555 0199',
  legalBusinessEmail: 'legal@orbit-demo.example',
  ownerName: 'Liina Kask',
  website: 'https://orbit-demo.example',
  staffSize: '65',
  paymentProducts: 'Cards, SEPA, bank wire',
  businessCategory: 'Regulated crypto-asset exchange',
  productsServices: 'Retail and institutional crypto on/off-ramp with custodial wallets.',
  goodsOrServicesType: 'Digital services',
  customerType: 'B2C and B2B',
  advancePayment: 'Yes',
  advancePaymentPercent: '100% prefunded trading balance',
  recurringBilling: 'No',
  recurringSalesPercent: '0%',
  fulfillmentTimeline: 'Instant — trades settle on exchange in seconds',

  generalEmail: 'hello@orbit-demo.example',
  supportEmail: 'support@orbit-demo.example',
  disputesEmail: 'disputes@orbit-demo.example',
  phone: '+372 555 0199',
  preferredContact: 'Email',
  socialPresence: 'X, LinkedIn, Telegram community',

  registeredAddress: 'Tornimäe 5, 10145',
  operatingAddress: 'Rotermanni 6, 10111 Tallinn (operations hub)',
  city: 'Tallinn',
  region: 'Harju',
  province: 'Harju maakond',
  operatingDiffers: 'yes',

  timeInBusiness: '7 years',
  targetGeography: 'EU / EEA + UK',
  deliveryMethod: 'N/A — digital exchange platform',
  domesticVsInternational: '30% domestic / 70% cross-border (intra-EU)',

  avgTxnCount: '18000',
  minTxnCount: '9000',
  maxTxnCount: '42000',
  avgTicketSize: '240',
  domesticCrossBorderSplit: '30% domestic / 70% cross-border',
  processingCurrencies: 'EUR, USD, GBP',
  highestTicketAmount: '25000',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Visa, Mastercard, SEPA Instant',
  recurringTransactionsPercent: '5%',
  foreignCardsPercent: '55%',

  cryptoServices: 'Spot trading, custodial wallets, fiat on/off-ramp',
  amlKycProcedures: 'Tier-1 KYC vendor + sanctions & PEP screening; ongoing txn monitoring.',
  cryptoLicenses: 'Estonia VASP license + MiCA authorisation in progress',
  custodyArrangement: 'Qualified third-party custodian for 95% of cold storage assets',

  ownershipPercentage: '45',
  beneficialOwners:
    'Liina Kask, 45%, CEO, liina@orbit-demo.example\nTomas Ilves, 30%, CTO, tomas@orbit-demo.example\nNordic Digital Ventures Fund II, 25%, Institutional investor, ir@orbit-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'Yes',
  nonOwnerControllerDetails: 'Ravi Shah, Chief Compliance Officer, ravi@orbit-demo.example',
  authorizedSignerName: 'Liina Kask',
  authorizedSignerTitle: 'CEO',
  authorizedSignerEmail: 'liina@orbit-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'CEO & Co-founder',
  ownerEmail: 'liina@orbit-demo.example',
  ownerIdNumber: 'PP-EE-DEMO-77102',
  ownerIdExpiry: '2030-05-05',
  ownerCountryOfResidence: 'EE',

  bankName: 'LHV Pank',
  accountHolderName: 'Orbit Exchange OÜ',
  accountNumber: 'EE**********1122 (demo)',
  routingNumber: 'LHVBEE22',
  settlementCurrency: 'EUR',

  complianceDetails:
    'ISO 27001 certified; SOC 2 Type II; dedicated AML team; Chainalysis KYT; annual pen tests.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Checkout.com',
  processorExitReason: 'Scaling beyond current limits; seeking higher-risk-tolerance acquirer.',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Checkout.com hosted fields + 3DS2',
  dataBreachHistory: 'No',
  regulatedBusiness: 'Yes',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

export const DEMO_PROFILES: DemoProfile[] = [
  {
    id: 'northwind-saas-ca',
    label: 'Northwind Analytics — SaaS (CA)',
    description: 'B2B SaaS, LLC, moderate volume, low-risk',
    data: northwindSaasCanada,
  },
  {
    id: 'bright-harbor-retail-us',
    label: 'Bright Harbor — Retail (US)',
    description: 'DTC e-commerce, Corp, higher volume',
    data: brightHarborRetailUs,
  },
  {
    id: 'helix-services-ca',
    label: 'Helix Pro — Services (CA)',
    description: 'Consulting LLP, low volume, multi-owner',
    data: helixProServicesCanada,
  },
  {
    id: 'orbit-crypto-eu',
    label: 'Orbit Exchange — Crypto (EU)',
    description: 'High-risk VASP, high volume, international',
    data: orbitExchangeCryptoEu,
  },
];

export const DEFAULT_DEMO_PROFILE_ID = DEMO_PROFILES[0]!.id;

export function getDemoProfile(id: string): DemoProfile {
  return DEMO_PROFILES.find((p) => p.id === id) ?? DEMO_PROFILES[0]!;
}

/** Backwards-compat export — equal to the first demo profile's data. */
export const demoMerchantData: MerchantData = DEMO_PROFILES[0]!.data;
