import type { MerchantData } from '@/src/types';
import { initialMerchantData } from '@/src/types';

/**
 * Demo profiles for presentations and manual testing.
 *
 * Pick a profile from the Merchant portal sidebar. The "Autofill" shortcut
 * then only fills the fields of the CURRENT intake step so you can step
 * through the wizard page by page with realistic values one page at a time.
 *
 * Text/dropdown/button questions fill a single field; form steps fill all
 * fields in that form. Files are intentionally left null so the Admin view
 * can still show "missing documents".
 *
 * Constrained select fields (common intake) use the exact option strings from
 * `commonQuestionBank.ts` so autofill never writes values the UI cannot select.
 */
export interface DemoProfile {
  id: string;
  label: string;
  description: string;
  data: MerchantData;
}

const northwindSaasCanada: MerchantData = {
  ...initialMerchantData,
  businessType: 'limited_liability',
  country: 'CA',
  industry: 'software',
  monthlyVolume: '10k-50k',
  monthlyTransactions: '100-1k',
  legalName: 'Northwind Analytics Inc.',
  dbaName: 'Northwind Analytics',
  taxId: 'BN 123456789',
  businessRegistrationNumber: 'BC1234567 / GST 123456789 RT0001',
  establishedDate: '2021-04-15',
  legalBusinessAddress: '400 Granville Street, Suite 1200, Vancouver, BC',
  operatingAddressDifferent: 'No',
  businessPhone: '+1 604 555 0142',
  legalBusinessEmail: 'legal@northwind-demo.example',
  ownerName: 'Alex Chen',
  website: 'https://northwind-demo.example',
  staffSize: '18',
  paymentProducts: 'Cards, ACH, Apple Pay',
  businessCategory: 'E-commerce',
  productsServices: 'SaaS subscription software',
  businessDescription: 'Digital-first with recurring revenue',
  goodsOrServicesType: 'Digital goods',
  customerType: 'B2B',
  advancePayment: 'Yes',
  advancePaymentPercent: '100% monthly subscription paid at billing date',
  recurringBilling: 'Yes',
  recurringSalesPercent: '95%',
  fulfillmentTimeline: 'Same day / instant',

  generalEmail: 'hello@northwind-demo.example',
  supportEmail: 'support@northwind-demo.example',
  disputesEmail: 'risk@northwind-demo.example',
  phone: '+1 604 555 0142',
  preferredContact: 'Email',
  socialPresence: 'LinkedIn, X',

  registeredAddress: '400 Granville Street, Suite 1200',
  operatingAddress: 'Same as registered',
  city: 'Vancouver',
  region: 'BC',
  province: 'British Columbia',
  operatingDiffers: 'no',

  timeInBusiness: '3 years',
  targetGeography: 'Canada & United States',
  deliveryMethod: 'N/A — digital product',
  domesticVsInternational: '85% domestic / 15% international',

  avgTxnCount: '450',
  minTxnCount: '200',
  maxTxnCount: '900',
  avgTicketSize: '89',
  domesticCrossBorderSplit: '85% domestic / 15% cross-border',
  processingCurrencies: 'CAD, USD',
  highestTicketAmount: '1200',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Visa / Mastercard / Amex',
  recurringTransactionsPercent: '76-100%',
  foreignCardsPercent: '11-25%',

  recurringBillingDetails: 'Monthly and annual SaaS subscriptions',
  trialPeriod: '14-day trial',
  refundPolicy: 'Pro-rated refunds within 30 days',
  shippingPolicy: 'N/A',

  ownershipPercentage: '100',
  beneficialOwners: 'Alex Chen, 100%, CEO & Founder, alex.chen@northwind-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Alex Chen',
  authorizedSignerTitle: 'CEO & Founder',
  authorizedSignerEmail: 'alex.chen@northwind-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'CEO & Founder',
  ownerEmail: 'alex.chen@northwind-demo.example',
  ownerIdNumber: 'DL-BC-DEMO-90210',
  ownerIdExpiry: '2028-06-30',
  ownerCountryOfResidence: 'CA',

  bankName: 'TD Canada Trust',
  accountHolderName: 'Northwind Analytics Inc.',
  accountNumber: '****4521 (demo)',
  routingNumber: '004',
  settlementCurrency: 'CAD',

  complianceDetails: 'SOC 2 Type II in progress; vendor security reviews annually.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Stripe',
  processorExitReason: 'Need better settlement / currency support',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Stripe + billing integration',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

const brightHarborRetailUs: MerchantData = {
  ...initialMerchantData,
  businessType: 'corporation',
  country: 'US',
  industry: 'retail',
  monthlyVolume: '50k-250k',
  monthlyTransactions: '1k-10k',
  legalName: 'Bright Harbor Goods, Inc.',
  dbaName: 'Bright Harbor',
  taxId: '47-8812993',
  businessRegistrationNumber: 'DE-4482217 / EIN 47-8812993',
  establishedDate: '2019-08-02',
  legalBusinessAddress: '221 W 4th Street, Suite 301, Wilmington, DE 19801',
  operatingAddressDifferent: 'Yes',
  businessPhone: '+1 302 555 0188',
  legalBusinessEmail: 'legal@brightharbor-demo.example',
  ownerName: 'Priya Natarajan',
  website: 'https://brightharbor-demo.example',
  staffSize: '42',
  paymentProducts: 'Cards, Apple Pay, Google Pay, Shop Pay',
  businessCategory: 'E-commerce',
  productsServices: 'Retail physical goods',
  businessDescription: 'Physical goods with fulfillment operations',
  goodsOrServicesType: 'Physical goods',
  customerType: 'B2C',
  advancePayment: 'No',
  advancePaymentPercent: '0%',
  recurringBilling: 'No',
  recurringSalesPercent: '0%',
  fulfillmentTimeline: '1-3 days',

  generalEmail: 'hello@brightharbor-demo.example',
  supportEmail: 'care@brightharbor-demo.example',
  disputesEmail: 'disputes@brightharbor-demo.example',
  phone: '+1 302 555 0188',
  preferredContact: 'Email',
  socialPresence: 'Instagram, TikTok, Pinterest',

  registeredAddress: '221 W 4th Street, Suite 301',
  operatingAddress: '880 Industrial Way, Reno, NV 89502 (fulfillment center)',
  city: 'Wilmington',
  region: 'DE',
  province: 'Delaware',
  operatingDiffers: 'yes',

  timeInBusiness: '6 years',
  targetGeography: 'United States (all 50 states) + limited CA shipping',
  deliveryMethod: 'In-house fulfillment + 3PL (ShipBob)',
  domesticVsInternational: '95% domestic / 5% cross-border',
  avgDeliveryTime: '3 business days',

  avgTxnCount: '3200',
  minTxnCount: '1800',
  maxTxnCount: '6500',
  avgTicketSize: '68',
  domesticCrossBorderSplit: '95% domestic / 5% cross-border',
  processingCurrencies: 'USD',
  highestTicketAmount: '840',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Full mix',
  recurringTransactionsPercent: '0%',
  foreignCardsPercent: '1-10%',

  refundPolicy: '30-day no-questions-asked returns, prepaid label included',
  shippingPolicy: 'Free US ground shipping on orders $50+',

  ownershipPercentage: '60',
  beneficialOwners:
    'Priya Natarajan, 60%, CEO, priya@brightharbor-demo.example\nMarcus Lee, 40%, COO, marcus@brightharbor-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Priya Natarajan',
  authorizedSignerTitle: 'CEO',
  authorizedSignerEmail: 'priya@brightharbor-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'CEO & Co-founder',
  ownerEmail: 'priya@brightharbor-demo.example',
  ownerIdNumber: 'DL-DE-DEMO-44219',
  ownerIdExpiry: '2029-02-14',
  ownerCountryOfResidence: 'US',

  bankName: 'Chase',
  accountHolderName: 'Bright Harbor Goods, Inc.',
  accountNumber: '****7788 (demo)',
  routingNumber: '021000021',
  settlementCurrency: 'USD',

  complianceDetails: 'PCI DSS SAQ A via Shopify; annual vendor security review.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Shopify Payments',
  processorExitReason: 'Lower processing cost / pricing',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Yes',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Shopify + payment apps',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

const helixProServicesCanada: MerchantData = {
  ...initialMerchantData,
  businessType: 'partnership',
  country: 'CA',
  industry: 'services',
  monthlyVolume: '<10k',
  monthlyTransactions: '<100',
  legalName: 'Helix Professional Services LLP',
  dbaName: 'Helix Pro',
  taxId: 'BN 998877665',
  businessRegistrationNumber: 'ON-LLP-2233445',
  establishedDate: '2023-01-10',
  legalBusinessAddress: '77 King Street West, Suite 2200, Toronto, ON',
  operatingAddressDifferent: 'No',
  businessPhone: '+1 416 555 0101',
  legalBusinessEmail: 'legal@helixpro-demo.example',
  ownerName: 'Dana Whitfield',
  website: 'https://helixpro-demo.example',
  staffSize: '4',
  paymentProducts: 'Cards, ACH',
  businessCategory: 'Service',
  productsServices: 'Professional services / consulting',
  businessDescription: 'Low-risk standard business model',
  goodsOrServicesType: 'Services',
  customerType: 'B2B',
  advancePayment: 'Yes',
  advancePaymentPercent: '50% deposit on engagement',
  recurringBilling: 'Yes',
  recurringSalesPercent: '60%',
  fulfillmentTimeline: '1-3 days',

  generalEmail: 'hello@helixpro-demo.example',
  supportEmail: 'clients@helixpro-demo.example',
  disputesEmail: 'billing@helixpro-demo.example',
  phone: '+1 416 555 0101',
  preferredContact: 'Email',
  socialPresence: 'LinkedIn',

  registeredAddress: '77 King Street West, Suite 2200',
  operatingAddress: 'Same as registered',
  city: 'Toronto',
  region: 'ON',
  province: 'Ontario',
  operatingDiffers: 'no',

  timeInBusiness: '2 years',
  targetGeography: 'Canada, primarily Ontario & BC',
  deliveryMethod: 'N/A — services engagement',
  domesticVsInternational: '100% domestic',

  avgTxnCount: '22',
  minTxnCount: '10',
  maxTxnCount: '45',
  avgTicketSize: '2800',
  domesticCrossBorderSplit: '100% domestic / 0% cross-border',
  processingCurrencies: 'CAD',
  highestTicketAmount: '12000',
  transactionChannelSplit: '33% card present / 33% e-commerce / 34% MOTO',
  paymentTypesWanted: 'Visa / Mastercard / Amex',
  recurringTransactionsPercent: '51-75%',
  foreignCardsPercent: '0%',

  serviceType: 'Fractional CFO retainer + project-based finance ops',
  billingModel: 'Monthly retainer + milestone billing',
  contractLength: '6 months',

  ownershipPercentage: '55',
  beneficialOwners:
    'Dana Whitfield, 55%, Managing Partner, dana@helixpro-demo.example\nJordan Park, 45%, Partner, jordan@helixpro-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Dana Whitfield',
  authorizedSignerTitle: 'Managing Partner',
  authorizedSignerEmail: 'dana@helixpro-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'Managing Partner',
  ownerEmail: 'dana@helixpro-demo.example',
  ownerIdNumber: 'DL-ON-DEMO-55117',
  ownerIdExpiry: '2027-11-20',
  ownerCountryOfResidence: 'CA',

  bankName: 'RBC Royal Bank',
  accountHolderName: 'Helix Professional Services LLP',
  accountNumber: '****0204 (demo)',
  routingNumber: '003',
  settlementCurrency: 'CAD',

  complianceDetails: 'Standard professional services engagement letters; no regulated activity.',
  currentlyProcessesCards: 'No',
  currentOrPreviousProcessor: 'No previous processor',
  processorExitReason: 'No prior processor',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Hosted checkout only',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Not applicable',
};

const orbitExchangeCryptoEu: MerchantData = {
  ...initialMerchantData,
  businessType: 'corporation',
  country: 'EU',
  industry: 'crypto',
  monthlyVolume: '>250k',
  monthlyTransactions: '>10k',
  legalName: 'Orbit Exchange OÜ',
  dbaName: 'Orbit',
  taxId: 'EE102334455',
  businessRegistrationNumber: 'EE-14778822 / VAT EE102334455',
  establishedDate: '2018-06-22',
  legalBusinessAddress: 'Tornimäe 5, 10145 Tallinn, Estonia',
  operatingAddressDifferent: 'Yes',
  businessPhone: '+372 555 0199',
  legalBusinessEmail: 'legal@orbit-demo.example',
  ownerName: 'Liina Kask',
  website: 'https://orbit-demo.example',
  staffSize: '65',
  paymentProducts: 'Cards, SEPA, bank wire',
  businessCategory: 'E-commerce',
  productsServices: 'Crypto exchange / wallet services',
  businessDescription: 'Regulated / high-risk with compliance controls',
  goodsOrServicesType: 'Digital goods',
  customerType: 'Both',
  advancePayment: 'Yes',
  advancePaymentPercent: '100% prefunded trading balance',
  recurringBilling: 'No',
  recurringSalesPercent: '0%',
  fulfillmentTimeline: 'Same day / instant',

  generalEmail: 'hello@orbit-demo.example',
  supportEmail: 'support@orbit-demo.example',
  disputesEmail: 'disputes@orbit-demo.example',
  phone: '+372 555 0199',
  preferredContact: 'Email',
  socialPresence: 'X, LinkedIn, Telegram community',

  registeredAddress: 'Tornimäe 5, 10145',
  operatingAddress: 'Rotermanni 6, 10111 Tallinn (operations hub)',
  city: 'Tallinn',
  region: 'Harju',
  province: 'Harju maakond',
  operatingDiffers: 'yes',

  timeInBusiness: '7 years',
  targetGeography: 'EU / EEA + UK',
  deliveryMethod: 'N/A — digital exchange platform',
  domesticVsInternational: '30% domestic / 70% cross-border (intra-EU)',

  avgTxnCount: '18000',
  minTxnCount: '9000',
  maxTxnCount: '42000',
  avgTicketSize: '240',
  domesticCrossBorderSplit: '30% domestic / 70% cross-border',
  processingCurrencies: 'EUR, USD, GBP',
  highestTicketAmount: '25000',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Visa / Mastercard',
  recurringTransactionsPercent: '1-10%',
  foreignCardsPercent: '51-75%',

  cryptoServices: 'Spot trading, custodial wallets, fiat on/off-ramp',
  amlKycProcedures: 'Tier-1 KYC vendor + sanctions & PEP screening; ongoing txn monitoring.',
  cryptoLicenses: 'Estonia VASP license + MiCA authorisation in progress',
  custodyArrangement: 'Qualified third-party custodian for 95% of cold storage assets',

  ownershipPercentage: '45',
  beneficialOwners:
    'Liina Kask, 45%, CEO, liina@orbit-demo.example\nTomas Ilves, 30%, CTO, tomas@orbit-demo.example\nNordic Digital Ventures Fund II, 25%, Institutional investor, ir@orbit-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'Yes',
  nonOwnerControllerDetails: 'Ravi Shah, Chief Compliance Officer, ravi@orbit-demo.example',
  authorizedSignerName: 'Liina Kask',
  authorizedSignerTitle: 'CEO',
  authorizedSignerEmail: 'liina@orbit-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'CEO & Co-founder',
  ownerEmail: 'liina@orbit-demo.example',
  ownerIdNumber: 'PP-EE-DEMO-77102',
  ownerIdExpiry: '2030-05-05',
  ownerCountryOfResidence: 'EE',

  bankName: 'LHV Pank',
  accountHolderName: 'Orbit Exchange OÜ',
  accountNumber: 'EE**********1122 (demo)',
  routingNumber: 'LHVBEE22',
  settlementCurrency: 'EUR',

  complianceDetails:
    'ISO 27001 certified; SOC 2 Type II; dedicated AML team; Chainalysis KYT; annual pen tests.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Checkout.com',
  processorExitReason: 'Better approval rate / risk appetite',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Gateway + fraud tooling',
  dataBreachHistory: 'No',
  regulatedBusiness: 'Yes',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

/** Micro sole prop — card-present heavy, low volume. */
const mapleLaneCafeCa: MerchantData = {
  ...initialMerchantData,
  businessType: 'sole_proprietorship',
  country: 'CA',
  industry: 'retail',
  monthlyVolume: '<10k',
  monthlyTransactions: '<100',
  legalName: 'Maple Lane Café (Sole Proprietorship)',
  dbaName: 'Maple Lane Café',
  taxId: 'BN 887766554',
  businessRegistrationNumber: 'BC Sole Prop registration on file (demo)',
  establishedDate: '2017-11-01',
  legalBusinessAddress: '88 Commercial Drive, Vancouver, BC',
  operatingAddressDifferent: 'No',
  businessPhone: '+1 604 555 0191',
  legalBusinessEmail: 'owner@maplelane-demo.example',
  ownerName: 'Sam Okonkwo',
  website: 'https://maplelane-demo.example',
  staffSize: '3',
  paymentProducts: 'Cards, Interac',
  businessCategory: 'Restaurant',
  productsServices: 'Retail physical goods',
  businessDescription: 'Low-risk standard business model',
  goodsOrServicesType: 'Mix',
  customerType: 'B2C',
  advancePayment: 'No',
  advancePaymentPercent: '0%',
  recurringBilling: 'No',
  recurringSalesPercent: '0%',
  fulfillmentTimeline: 'Same day / instant',

  generalEmail: 'hello@maplelane-demo.example',
  supportEmail: 'hello@maplelane-demo.example',
  disputesEmail: 'hello@maplelane-demo.example',
  phone: '+1 604 555 0191',
  preferredContact: 'Email',
  socialPresence: 'Instagram',

  registeredAddress: '88 Commercial Drive',
  operatingAddress: 'Same as registered',
  city: 'Vancouver',
  region: 'BC',
  province: 'British Columbia',
  operatingDiffers: 'no',

  timeInBusiness: '8 years',
  targetGeography: 'Neighborhood + tourists',
  deliveryMethod: 'Counter service and takeout',
  domesticVsInternational: '100% domestic',

  avgTxnCount: '420',
  minTxnCount: '200',
  maxTxnCount: '900',
  avgTicketSize: '18',
  domesticCrossBorderSplit: '100% domestic / 0% cross-border',
  processingCurrencies: 'CAD',
  highestTicketAmount: '120',
  transactionChannelSplit: '70% card present / 25% e-commerce / 5% MOTO',
  paymentTypesWanted: 'Cards + Interac',
  recurringTransactionsPercent: '0%',
  foreignCardsPercent: '1-10%',

  ownershipPercentage: '100',
  beneficialOwners: 'Sam Okonkwo, 100%, Owner, sam@maplelane-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Sam Okonkwo',
  authorizedSignerTitle: 'Owner',
  authorizedSignerEmail: 'sam@maplelane-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'Owner',
  ownerEmail: 'sam@maplelane-demo.example',
  ownerIdNumber: 'DL-BC-DEMO-11002',
  ownerIdExpiry: '2029-03-01',
  ownerCountryOfResidence: 'CA',

  bankName: 'Coast Capital Savings',
  accountHolderName: 'Sam Okonkwo',
  accountNumber: '****9012 (demo)',
  routingNumber: '809',
  settlementCurrency: 'CAD',

  complianceDetails: 'Local food service; no regulated financial products.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Square',
  processorExitReason: 'Lower processing cost / pricing',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'None',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

/** Non-profit — mid volume donations & program fees. */
const riverbankHousingSocietyCa: MerchantData = {
  ...initialMerchantData,
  businessType: 'non_profit',
  country: 'CA',
  industry: 'services',
  monthlyVolume: '10k-50k',
  monthlyTransactions: '100-1k',
  legalName: 'Riverbank Housing Society',
  dbaName: 'Riverbank Programs',
  taxId: 'BN 776655443',
  businessRegistrationNumber: 'BC Society file #NP-DEMO-7788',
  establishedDate: '2005-06-15',
  legalBusinessAddress: '1200 Burrard Street, Vancouver, BC',
  operatingAddressDifferent: 'No',
  businessPhone: '+1 604 555 0177',
  legalBusinessEmail: 'finance@riverbank-demo.example',
  ownerName: 'Morgan Patel',
  website: 'https://riverbank-demo.example',
  staffSize: '28',
  paymentProducts: 'Cards, ACH',
  businessCategory: 'Service',
  productsServices: 'Professional services / consulting',
  businessDescription: 'Low-risk standard business model',
  goodsOrServicesType: 'Services',
  customerType: 'B2C',
  advancePayment: 'No',
  advancePaymentPercent: '0%',
  recurringBilling: 'Yes',
  recurringSalesPercent: '40%',
  fulfillmentTimeline: '1-3 days',

  generalEmail: 'info@riverbank-demo.example',
  supportEmail: 'support@riverbank-demo.example',
  disputesEmail: 'finance@riverbank-demo.example',
  phone: '+1 604 555 0177',
  preferredContact: 'Email',
  socialPresence: 'LinkedIn, Facebook',

  registeredAddress: '1200 Burrard Street',
  operatingAddress: 'Same as registered',
  city: 'Vancouver',
  region: 'BC',
  province: 'British Columbia',
  operatingDiffers: 'no',

  timeInBusiness: '19 years',
  targetGeography: 'Metro Vancouver',
  deliveryMethod: 'Program enrollment and housing intake (in-person + portal)',
  domesticVsInternational: '100% domestic',

  avgTxnCount: '380',
  minTxnCount: '120',
  maxTxnCount: '900',
  avgTicketSize: '95',
  domesticCrossBorderSplit: '100% domestic / 0% cross-border',
  processingCurrencies: 'CAD',
  highestTicketAmount: '2500',
  transactionChannelSplit: '10% card present / 85% e-commerce / 5% MOTO',
  paymentTypesWanted: 'Cards + ACH / bank debit',
  recurringTransactionsPercent: '26-50%',
  foreignCardsPercent: '0%',

  ownershipPercentage: '0',
  beneficialOwners: 'Board Treasurer, Riverbank Housing Society, 0%, Treasurer, treasurer@riverbank-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'Yes',
  nonOwnerControllerDetails: 'Jamie Ng, Executive Director, director@riverbank-demo.example',
  authorizedSignerName: 'Morgan Patel',
  authorizedSignerTitle: 'CFO',
  authorizedSignerEmail: 'finance@riverbank-demo.example',
  signerIsOwner: 'No',
  ownerRole: 'Board liaison',
  ownerEmail: 'morgan@riverbank-demo.example',
  ownerIdNumber: 'DL-BC-DEMO-44100',
  ownerIdExpiry: '2028-01-15',
  ownerCountryOfResidence: 'CA',

  bankName: 'Vancity',
  accountHolderName: 'Riverbank Housing Society',
  accountNumber: '****3300 (demo)',
  routingNumber: '839',
  settlementCurrency: 'CAD',

  complianceDetails: 'Registered BC non-profit; annual audited financials.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Stripe',
  processorExitReason: 'Feature gaps (subscriptions, reporting, routing)',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Stripe + billing integration',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

/** Government entity — low volume program payments. */
const civicPayServicesCa: MerchantData = {
  ...initialMerchantData,
  businessType: 'government',
  country: 'CA',
  industry: 'services',
  monthlyVolume: '<10k',
  monthlyTransactions: '<100',
  legalName: 'City of Portwell — Finance Services',
  dbaName: 'CivicPay Online',
  taxId: 'BN 665544332',
  businessRegistrationNumber: 'Municipal charter reference PW-MUN-DEMO-01',
  establishedDate: '1998-01-01',
  legalBusinessAddress: '1 City Hall Square, Portwell, BC',
  operatingAddressDifferent: 'No',
  businessPhone: '+1 250 555 0144',
  legalBusinessEmail: 'treasury@civicpay-demo.example',
  ownerName: 'Taylor Brooks',
  website: 'https://civicpay-demo.example',
  staffSize: '220',
  paymentProducts: 'Cards, Interac',
  businessCategory: 'Service',
  productsServices: 'Other standardized profile',
  businessDescription: 'Low-risk standard business model',
  goodsOrServicesType: 'Services',
  customerType: 'B2C',
  advancePayment: 'Yes',
  advancePaymentPercent: '100% due at time of permit / license application',
  recurringBilling: 'No',
  recurringSalesPercent: '0%',
  fulfillmentTimeline: 'Same day / instant',

  generalEmail: 'service@civicpay-demo.example',
  supportEmail: 'service@civicpay-demo.example',
  disputesEmail: 'treasury@civicpay-demo.example',
  phone: '+1 250 555 0144',
  preferredContact: 'Email',
  socialPresence: 'City website',

  registeredAddress: '1 City Hall Square',
  operatingAddress: 'Same as registered',
  city: 'Portwell',
  region: 'BC',
  province: 'British Columbia',
  operatingDiffers: 'no',

  timeInBusiness: '27 years',
  targetGeography: 'Municipal residents and businesses',
  deliveryMethod: 'Online portal + in-person counters',
  domesticVsInternational: '99% domestic / 1% cross-border',

  avgTxnCount: '55',
  minTxnCount: '20',
  maxTxnCount: '120',
  avgTicketSize: '145',
  domesticCrossBorderSplit: '99% domestic / 1% cross-border',
  processingCurrencies: 'CAD',
  highestTicketAmount: '5000',
  transactionChannelSplit: '20% card present / 75% e-commerce / 5% MOTO',
  paymentTypesWanted: 'Cards + Interac',
  recurringTransactionsPercent: '0%',
  foreignCardsPercent: '1-10%',

  ownershipPercentage: '0',
  beneficialOwners: 'City Treasurer office, 0%, Authorized officer, treasury@civicpay-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Taylor Brooks',
  authorizedSignerTitle: 'Director of Treasury',
  authorizedSignerEmail: 'treasury@civicpay-demo.example',
  signerIsOwner: 'No',
  ownerRole: 'Program coordinator',
  ownerEmail: 'taylor.brooks@civicpay-demo.example',
  ownerIdNumber: 'GOV-ID-BC-DEMO-22001',
  ownerIdExpiry: '2031-12-31',
  ownerCountryOfResidence: 'CA',

  bankName: 'Bank of Montreal',
  accountHolderName: 'City of Portwell',
  accountNumber: '****6600 (demo)',
  routingNumber: '001',
  settlementCurrency: 'CAD',

  complianceDetails: 'Public sector procurement; segregated merchant account for online fees.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Adyen',
  processorExitReason: 'Support or service quality issues',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Other standardized stack',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

/** Parent-owned enterprise — large B2B SaaS under a holding company. */
const cascadeSoftwareParentUs: MerchantData = {
  ...initialMerchantData,
  businessType: 'parent_owned',
  country: 'US',
  industry: 'software',
  monthlyVolume: '>250k',
  monthlyTransactions: '>10k',
  legalName: 'Cascade Metrics LLC',
  dbaName: 'Cascade Metrics',
  taxId: '88-1029384',
  businessRegistrationNumber: 'DE LLC file #CM-998877 / EIN 88-1029384',
  establishedDate: '2014-03-22',
  legalBusinessAddress: '1313 Innovation Way, Austin, TX 78701',
  operatingAddressDifferent: 'Yes',
  businessPhone: '+1 512 555 0166',
  legalBusinessEmail: 'legal@cascade-demo.example',
  ownerName: 'Riley Stone',
  website: 'https://cascade-demo.example',
  staffSize: '480',
  paymentProducts: 'Cards, ACH, wire',
  businessCategory: 'E-commerce',
  productsServices: 'SaaS subscription software',
  businessDescription: 'Digital-first with recurring revenue',
  goodsOrServicesType: 'Digital goods',
  customerType: 'B2B',
  advancePayment: 'Yes',
  advancePaymentPercent: 'Annual contracts billed quarterly',
  recurringBilling: 'Yes',
  recurringSalesPercent: '92%',
  fulfillmentTimeline: 'Same day / instant',

  generalEmail: 'hello@cascade-demo.example',
  supportEmail: 'support@cascade-demo.example',
  disputesEmail: 'legal@cascade-demo.example',
  phone: '+1 512 555 0166',
  preferredContact: 'Email',
  socialPresence: 'LinkedIn, X',

  registeredAddress: '1313 Innovation Way, Suite 400',
  operatingAddress: '90 Fifth Avenue, New York, NY 10011 (HQ)',
  city: 'Austin',
  region: 'TX',
  province: 'Texas',
  operatingDiffers: 'yes',

  timeInBusiness: '11 years',
  targetGeography: 'North America + EU expansion',
  deliveryMethod: 'Cloud-hosted software',
  domesticVsInternational: '70% domestic / 30% international',

  avgTxnCount: '42000',
  minTxnCount: '20000',
  maxTxnCount: '95000',
  avgTicketSize: '420',
  domesticCrossBorderSplit: '70% domestic / 30% cross-border',
  processingCurrencies: 'USD, EUR',
  highestTicketAmount: '85000',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Full mix',
  recurringTransactionsPercent: '76-100%',
  foreignCardsPercent: '26-50%',

  ownershipPercentage: '100',
  beneficialOwners:
    'Riley Stone, 8%, President, riley@cascade-demo.example\nNorthloom Holdings Inc., 92%, Parent investor, holding@northloom-demo.example',
  parentOwned: 'Yes',
  parentCompanyName: 'Northloom Holdings Inc.',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Riley Stone',
  authorizedSignerTitle: 'President',
  authorizedSignerEmail: 'riley@cascade-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'President',
  ownerEmail: 'riley@cascade-demo.example',
  ownerIdNumber: 'DL-TX-DEMO-77112',
  ownerIdExpiry: '2030-08-20',
  ownerCountryOfResidence: 'US',

  bankName: 'Wells Fargo',
  accountHolderName: 'Cascade Metrics LLC',
  accountNumber: '****5544 (demo)',
  routingNumber: '111000025',
  settlementCurrency: 'USD',

  complianceDetails: 'SOC 2 Type II; vendor risk program; annual penetration testing.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Stripe',
  processorExitReason: 'Feature gaps (subscriptions, reporting, routing)',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Stripe + billing integration',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

/** UK mid-market gaming — digital goods + compliance-heavy. */
const pixelArenaGamingUk: MerchantData = {
  ...initialMerchantData,
  businessType: 'corporation',
  country: 'UK',
  industry: 'gaming',
  monthlyVolume: '50k-250k',
  monthlyTransactions: '1k-10k',
  legalName: 'Pixel Arena Studios Ltd',
  dbaName: 'Pixel Arena',
  taxId: 'GB 123 4567 89',
  businessRegistrationNumber: 'Companies House #PA-DEMO-889900',
  establishedDate: '2016-09-12',
  legalBusinessAddress: '45 Shoreditch High Street, London, E1 6JE, UK',
  operatingAddressDifferent: 'No',
  businessPhone: '+44 20 5555 0140',
  legalBusinessEmail: 'legal@pixelarena-demo.example',
  ownerName: 'Aisha Khan',
  website: 'https://pixelarena-demo.example',
  staffSize: '85',
  paymentProducts: 'Cards, Apple Pay, Google Pay',
  businessCategory: 'E-commerce',
  productsServices: 'Gaming / digital entertainment',
  businessDescription: 'Regulated / high-risk with compliance controls',
  goodsOrServicesType: 'Digital goods',
  customerType: 'B2C',
  advancePayment: 'Yes',
  advancePaymentPercent: '100% at checkout for digital items',
  recurringBilling: 'Yes',
  recurringSalesPercent: '35%',
  fulfillmentTimeline: 'Same day / instant',

  generalEmail: 'hello@pixelarena-demo.example',
  supportEmail: 'support@pixelarena-demo.example',
  disputesEmail: 'trust@pixelarena-demo.example',
  phone: '+44 20 5555 0140',
  preferredContact: 'Email',
  socialPresence: 'Discord, X, Twitch',

  registeredAddress: '45 Shoreditch High Street',
  operatingAddress: 'Same as registered',
  city: 'London',
  region: 'ENG',
  province: 'England',
  operatingDiffers: 'no',

  timeInBusiness: '8 years',
  targetGeography: 'UK + EEA',
  deliveryMethod: 'Digital delivery via platform accounts',
  domesticVsInternational: '80% domestic / 20% international',

  avgTxnCount: '5200',
  minTxnCount: '2000',
  maxTxnCount: '11000',
  avgTicketSize: '22',
  domesticCrossBorderSplit: '80% domestic / 20% cross-border',
  processingCurrencies: 'GBP, EUR',
  highestTicketAmount: '499',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Visa / Mastercard / Amex',
  recurringTransactionsPercent: '26-50%',
  foreignCardsPercent: '11-25%',

  gamingType: 'Skill-based tournaments and cosmetic IAP',
  gamingLicenses: 'UKGC pathway under review (demo)',
  responsibleGaming: 'Deposit limits, cooling-off, self-exclusion',
  ageVerification: 'KYC + document checks at signup',

  ownershipPercentage: '100',
  beneficialOwners: 'Aisha Khan, 100%, CEO, aisha@pixelarena-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Aisha Khan',
  authorizedSignerTitle: 'CEO',
  authorizedSignerEmail: 'aisha@pixelarena-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'CEO',
  ownerEmail: 'aisha@pixelarena-demo.example',
  ownerIdNumber: 'UK-PASS-DEMO-PA-771',
  ownerIdExpiry: '2032-04-10',
  ownerCountryOfResidence: 'UK',

  bankName: 'Barclays',
  accountHolderName: 'Pixel Arena Studios Ltd',
  accountNumber: '****8821 (demo)',
  routingNumber: 'BUKBGB22',
  settlementCurrency: 'GBP',

  complianceDetails: 'AML program, sanctions screening, fraud monitoring, responsible gaming controls.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Adyen',
  processorExitReason: 'Better approval rate / risk appetite',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Gateway + fraud tooling',
  dataBreachHistory: 'No',
  regulatedBusiness: 'Yes',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

/** Other high risk — supplements / nutraceuticals, US mid-market. */
const apexNutraceuticalsUs: MerchantData = {
  ...initialMerchantData,
  businessType: 'corporation',
  country: 'US',
  industry: 'high_risk',
  monthlyVolume: '10k-50k',
  monthlyTransactions: '100-1k',
  legalName: 'Apex Nutraceuticals LLC',
  dbaName: 'Apex Labs Store',
  taxId: '55-6677889',
  businessRegistrationNumber: 'WY LLC #AX-DEMO-221100',
  establishedDate: '2020-02-18',
  legalBusinessAddress: '500 Capitol Avenue, Cheyenne, WY 82001',
  operatingAddressDifferent: 'No',
  businessPhone: '+1 307 555 0133',
  legalBusinessEmail: 'compliance@apex-demo.example',
  ownerName: 'Chris Vega',
  website: 'https://apex-demo.example',
  staffSize: '14',
  paymentProducts: 'Cards, ACH',
  businessCategory: 'E-commerce',
  productsServices: 'Other standardized profile',
  businessDescription: 'Regulated / high-risk with compliance controls',
  goodsOrServicesType: 'Physical goods',
  customerType: 'B2C',
  advancePayment: 'Yes',
  advancePaymentPercent: '100% at checkout',
  recurringBilling: 'Yes',
  recurringSalesPercent: '25%',
  fulfillmentTimeline: '4-7 days',

  generalEmail: 'hello@apex-demo.example',
  supportEmail: 'support@apex-demo.example',
  disputesEmail: 'chargebacks@apex-demo.example',
  phone: '+1 307 555 0133',
  preferredContact: 'Email',
  socialPresence: 'Instagram, TikTok',

  registeredAddress: '500 Capitol Avenue',
  operatingAddress: 'Same as registered',
  city: 'Cheyenne',
  region: 'WY',
  province: 'Wyoming',
  operatingDiffers: 'no',

  timeInBusiness: '5 years',
  targetGeography: 'United States',
  deliveryMethod: '3PL fulfillment (US)',
  domesticVsInternational: '98% domestic / 2% cross-border',

  avgTxnCount: '650',
  minTxnCount: '200',
  maxTxnCount: '1400',
  avgTicketSize: '78',
  domesticCrossBorderSplit: '98% domestic / 2% cross-border',
  processingCurrencies: 'USD',
  highestTicketAmount: '420',
  transactionChannelSplit: '0% card present / 100% e-commerce / 0% MOTO',
  paymentTypesWanted: 'Visa / Mastercard / Amex',
  recurringTransactionsPercent: '11-25%',
  foreignCardsPercent: '1-10%',

  regulatoryStatus: 'Dietary supplement labeling compliant; third-party COAs on file (demo).',
  chargebackHistory: 'Under 0.9% trailing 12 months',

  ownershipPercentage: '100',
  beneficialOwners: 'Chris Vega, 100%, Owner, chris@apex-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Chris Vega',
  authorizedSignerTitle: 'Owner',
  authorizedSignerEmail: 'chris@apex-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'Owner',
  ownerEmail: 'chris@apex-demo.example',
  ownerIdNumber: 'DL-WY-DEMO-44112',
  ownerIdExpiry: '2029-09-09',
  ownerCountryOfResidence: 'US',

  bankName: 'US Bank',
  accountHolderName: 'Apex Nutraceuticals LLC',
  accountNumber: '****1199 (demo)',
  routingNumber: '091000022',
  settlementCurrency: 'USD',

  complianceDetails: 'Chargeback monitoring, product compliance reviews, refund policy published.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Authorize.net',
  processorExitReason: 'Better approval rate / risk appetite',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Yes',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Hosted checkout only',
  dataBreachHistory: 'No',
  regulatedBusiness: 'Yes',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

/** Small UK retail — bricks + light e-commerce. */
const thamesGiftsUk: MerchantData = {
  ...initialMerchantData,
  businessType: 'limited_liability',
  country: 'UK',
  industry: 'retail',
  monthlyVolume: '<10k',
  monthlyTransactions: '<100',
  legalName: 'Thames Gifts Ltd',
  dbaName: 'Thames Gifts',
  taxId: 'GB 998 8776 54',
  businessRegistrationNumber: 'Companies House #TG-DEMO-445566',
  establishedDate: '2022-05-01',
  legalBusinessAddress: '12 Borough Market, London, SE1 9AH, UK',
  operatingAddressDifferent: 'No',
  businessPhone: '+44 20 5555 0188',
  legalBusinessEmail: 'shop@thamesgifts-demo.example',
  ownerName: 'Emma Wright',
  website: 'https://thamesgifts-demo.example',
  staffSize: '5',
  paymentProducts: 'Cards, Apple Pay',
  businessCategory: 'Retail',
  productsServices: 'Retail physical goods',
  businessDescription: 'Physical goods with fulfillment operations',
  goodsOrServicesType: 'Physical goods',
  customerType: 'B2C',
  advancePayment: 'No',
  advancePaymentPercent: '0%',
  recurringBilling: 'No',
  recurringSalesPercent: '0%',
  fulfillmentTimeline: '1-3 days',

  generalEmail: 'hello@thamesgifts-demo.example',
  supportEmail: 'hello@thamesgifts-demo.example',
  disputesEmail: 'hello@thamesgifts-demo.example',
  phone: '+44 20 5555 0188',
  preferredContact: 'Email',
  socialPresence: 'Instagram',

  registeredAddress: '12 Borough Market',
  operatingAddress: 'Same as registered',
  city: 'London',
  region: 'ENG',
  province: 'England',
  operatingDiffers: 'no',

  timeInBusiness: '3 years',
  targetGeography: 'Greater London tourists',
  deliveryMethod: 'In-store + Royal Mail tracked',
  domesticVsInternational: '95% domestic / 5% international',

  avgTxnCount: '380',
  minTxnCount: '120',
  maxTxnCount: '900',
  avgTicketSize: '42',
  domesticCrossBorderSplit: '95% domestic / 5% cross-border',
  processingCurrencies: 'GBP',
  highestTicketAmount: '280',
  transactionChannelSplit: '60% card present / 35% e-commerce / 5% MOTO',
  paymentTypesWanted: 'Visa / Mastercard',
  recurringTransactionsPercent: '0%',
  foreignCardsPercent: '1-10%',

  ownershipPercentage: '100',
  beneficialOwners: 'Emma Wright, 100%, Director, emma@thamesgifts-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Emma Wright',
  authorizedSignerTitle: 'Director',
  authorizedSignerEmail: 'emma@thamesgifts-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'Director',
  ownerEmail: 'emma@thamesgifts-demo.example',
  ownerIdNumber: 'UK-LIC-DEMO-TG-902',
  ownerIdExpiry: '2031-01-20',
  ownerCountryOfResidence: 'UK',

  bankName: 'Monzo Business',
  accountHolderName: 'Thames Gifts Ltd',
  accountNumber: '****7781 (demo)',
  routingNumber: 'MONZGB2L',
  settlementCurrency: 'GBP',

  complianceDetails: 'Retail gift shop; standard consumer protections.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Square',
  processorExitReason: 'Lower processing cost / pricing',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Yes',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Shopify + payment apps',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

/** International “Other” region — triggers enhanced verification path in legacy sequence. */
const pacificFreightOther: MerchantData = {
  ...initialMerchantData,
  businessType: 'partnership',
  country: 'Other',
  industry: 'services',
  monthlyVolume: '50k-250k',
  monthlyTransactions: '1k-10k',
  legalName: 'Pacific Rim Freight Partners',
  dbaName: 'Pacific Rim Freight',
  taxId: 'SG-UEN-DEMO-201988802K',
  businessRegistrationNumber: 'Singapore UEN 201988802K (demo)',
  establishedDate: '2011-07-19',
  legalBusinessAddress: '8 Marina Boulevard, #15-01, Singapore 018981',
  operatingAddressDifferent: 'Yes',
  businessPhone: '+65 6555 0100',
  legalBusinessEmail: 'legal@pacificfreight-demo.example',
  ownerName: 'Kenji Morita',
  website: 'https://pacificfreight-demo.example',
  staffSize: '95',
  paymentProducts: 'Cards, wire',
  businessCategory: 'Service',
  productsServices: 'Professional services / consulting',
  businessDescription: 'Mixed channels and mixed customer types',
  goodsOrServicesType: 'Services',
  customerType: 'Both',
  advancePayment: 'Yes',
  advancePaymentPercent: '30% deposit on booking',
  recurringBilling: 'No',
  recurringSalesPercent: '0%',
  fulfillmentTimeline: '8-30 days',

  generalEmail: 'ops@pacificfreight-demo.example',
  supportEmail: 'support@pacificfreight-demo.example',
  disputesEmail: 'legal@pacificfreight-demo.example',
  phone: '+65 6555 0100',
  preferredContact: 'Email',
  socialPresence: 'LinkedIn',

  registeredAddress: '8 Marina Boulevard, #15-01',
  operatingAddress: 'Warehouse hub: 22 Changi Coast Road, Singapore 499654',
  city: 'Singapore',
  region: 'SG',
  province: 'Singapore',
  operatingDiffers: 'yes',

  timeInBusiness: '14 years',
  targetGeography: 'APAC trade lanes',
  deliveryMethod: 'Freight forwarding + customs brokerage',
  domesticVsInternational: '20% domestic / 80% international',

  avgTxnCount: '2400',
  minTxnCount: '900',
  maxTxnCount: '5200',
  avgTicketSize: '1850',
  domesticCrossBorderSplit: '20% domestic / 80% cross-border',
  processingCurrencies: 'USD, SGD',
  highestTicketAmount: '45000',
  transactionChannelSplit: '5% card present / 90% e-commerce / 5% MOTO',
  paymentTypesWanted: 'Full mix',
  recurringTransactionsPercent: '0%',
  foreignCardsPercent: '51-75%',

  ownershipPercentage: '50',
  beneficialOwners:
    'Kenji Morita, 50%, Managing Partner, kenji@pacificfreight-demo.example\nSofia Alvarez, 50%, Managing Partner, sofia@pacificfreight-demo.example',
  parentOwned: 'No',
  parentCompanyName: '',
  nonOwnerController: 'No',
  nonOwnerControllerDetails: '',
  authorizedSignerName: 'Kenji Morita',
  authorizedSignerTitle: 'Managing Partner',
  authorizedSignerEmail: 'kenji@pacificfreight-demo.example',
  signerIsOwner: 'Yes',
  ownerRole: 'Managing Partner',
  ownerEmail: 'kenji@pacificfreight-demo.example',
  ownerIdNumber: 'PP-SG-DEMO-PR-771',
  ownerIdExpiry: '2033-06-01',
  ownerCountryOfResidence: 'Singapore',

  bankName: 'DBS Bank',
  accountHolderName: 'Pacific Rim Freight Partners',
  accountNumber: '****4422 (demo)',
  routingNumber: 'DBSSSGSG',
  settlementCurrency: 'USD',

  complianceDetails: 'Trade compliance screening; sanctions checks on counterparties.',
  currentlyProcessesCards: 'Yes',
  currentOrPreviousProcessor: 'Adyen',
  processorExitReason: 'Need better settlement / currency support',
  priorTermination: 'No',
  bankruptcyHistory: 'No',
  riskProgramHistory: 'No',
  websitePrivacyPolicy: 'Yes',
  websiteTerms: 'Yes',
  websiteRefundPolicy: 'Yes',
  websiteShippingPolicy: 'Not applicable',
  websiteContactInfo: 'Yes',
  websiteCurrencyDisplay: 'Yes',
  websiteSsl: 'Yes',
  storesCardNumbers: 'No',
  thirdPartyCardApps: 'Gateway + fraud tooling',
  dataBreachHistory: 'No',
  regulatedBusiness: 'No',
  canProvideRegistration: 'Yes',
  canProvideVoidCheque: 'Yes',
  canProvideBankStatements: 'Yes',
  canProvideProofOfAddress: 'Yes',
  canProvideProofOfOwnership: 'Yes',
  canProvideOwnerIds: 'Yes',
  canProvideProcessingStatements: 'Yes',
};

export const DEMO_PROFILES: DemoProfile[] = [
  {
    id: 'northwind-saas-ca',
    label: 'Northwind Analytics — SaaS (CA)',
    description: 'B2B SaaS, limited liability, moderate volume, low-risk',
    data: northwindSaasCanada,
  },
  {
    id: 'maple-lane-cafe-ca',
    label: 'Maple Lane Café — Sole prop (CA)',
    description: 'Micro retail / restaurant, sole prop, card-present heavy',
    data: mapleLaneCafeCa,
  },
  {
    id: 'thames-gifts-uk',
    label: 'Thames Gifts — Retail (UK)',
    description: 'Small bricks + e-commerce, limited liability',
    data: thamesGiftsUk,
  },
  {
    id: 'helix-services-ca',
    label: 'Helix Pro — Services (CA)',
    description: 'Consulting LLP, low volume, multi-owner',
    data: helixProServicesCanada,
  },
  {
    id: 'bright-harbor-retail-us',
    label: 'Bright Harbor — Retail (US)',
    description: 'DTC e-commerce, Corp, higher volume',
    data: brightHarborRetailUs,
  },
  {
    id: 'riverbank-housing-ca',
    label: 'Riverbank Housing — Non-profit (CA)',
    description: 'Registered society, program fees, board / staff signers',
    data: riverbankHousingSocietyCa,
  },
  {
    id: 'civic-pay-government-ca',
    label: 'CivicPay — Government (CA)',
    description: 'Municipal program payments, low volume, public sector',
    data: civicPayServicesCa,
  },
  {
    id: 'cascade-parent-software-us',
    label: 'Cascade Metrics — Parent-owned SaaS (US)',
    description: 'Enterprise-scale B2B SaaS under a holding company',
    data: cascadeSoftwareParentUs,
  },
  {
    id: 'pixelarena-gaming-uk',
    label: 'Pixel Arena — Gaming (UK)',
    description: 'Mid-market digital entertainment, compliance-heavy',
    data: pixelArenaGamingUk,
  },
  {
    id: 'apex-highrisk-us',
    label: 'Apex Labs — Other high risk (US)',
    description: 'Nutraceuticals e-commerce, elevated underwriting profile',
    data: apexNutraceuticalsUs,
  },
  {
    id: 'orbit-crypto-eu',
    label: 'Orbit Exchange — Crypto (EU)',
    description: 'High-risk VASP, high volume, international',
    data: orbitExchangeCryptoEu,
  },
  {
    id: 'pacific-freight-other',
    label: 'Pacific Rim Freight — Services (Other)',
    description: 'Cross-border logistics partnership, non-CA/US/EU/UK anchor',
    data: pacificFreightOther,
  },
];

export const DEFAULT_DEMO_PROFILE_ID = DEMO_PROFILES[0]!.id;

export function getDemoProfile(id: string): DemoProfile {
  return DEMO_PROFILES.find((p) => p.id === id) ?? DEMO_PROFILES[0]!;
}

/** Backwards-compat export — equal to the first demo profile's data. */
export const demoMerchantData: MerchantData = DEMO_PROFILES[0]!.data;
